sudo: required
language: bash
services:
- docker
before_script:
- docker-compose build r-transformation
script: docker-compose run --rm --entrypoint sh -e KBC_DATA_DIR=/code/tests/data/
  r-transformation /code/run_tests.sh
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notification:
  slack:
    secure: dCz4Zae8Y++STRscF5VHRUJA39HTHVkKlLtE/5wAvAOaJrheF8oaN9QjvNSAD6ev+ebr7vfGBHiTNjP/3x/1Z3y+qq+szt59VUnEbYUrfT0TY6GdNee6ozNm3fC84idXBqjyL1PE67dcfQFLnxkwq8AipamkFsP4dJNCCaKbR8clixOeLSmEoBJ/oPCDTFA6fatA+886h36wn8lnv/3K9LHpuyK/sdfaMVRVWR1h+qWKNpJQc2y5NW4LYH2zfokmSbtoPPsh87m/jq5TCyzLy+y38v568xrLa90IFPLe8Xj+D/ZGk54GF+iVYet84LUcxVHT67AUiy/TJ0DhmNmjd39h4A74UUY2h5HM6H0HTtu18nEbRI8DciLp6QJhgAY1mE2Ebf48SCcgTmIOD9WylSY3rklHmuu8Eg4PYaahQI9+CmKOVYg37xPEfoNgelOQmb3DUh4VT8MLjKrYIgx4/IUzlvG+JidJn7hRlpqUo5Ptpzrdpx1/dJepJoRXB3E8m8qiOoUi6C/jbE8jqCZbR62CYSamEAxZfvDNMDU9wXnbSPBmvbDKyECzKDWF8BfQm0Yo1KWuGnxwU9d/1UhMDKngF7opIBNx5Al1lwf7f3Yo67jN3s2Dv5ezUclJ+vR/UP/Lg1UuTzsXkhtPi2mOkikFUPo6FkcMXGe6ohw19AA=
  email: false
