sudo: required
language: bash
services:
- docker
before_script:
- docker-compose build r-transformation
script: docker-compose run --rm --entrypoint sh -e KBC_DATA_DIR=/code/tests/data/
  r-transformation /code/run_tests.sh
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notification:
  slack:
    secure: URSy9DsdC7yNVRKL3JM8OVP6T/f/3AsPe7FsNP+Cwe5e6IzGrxBCkOZX4zxPXmoKbj0VJeXQ4OfTNyzrOXmRv2sysVHCL7fo9JI1cpQnokwaWxUoWgaYA+BbjHM28GIzk6lcUuJeZ6Xm6IBfdKct7T3g0nGbp6m2YkpZ6UwfEHh/mEQmJ/5lYlCkjpamuDcbVXwFa7yndSN8MH7qfQk1VoTaqtbRB/xRAaNKFCwHaMrqN3/ljfrPpv6mr+DS1AcFIlXrVx49rNVZF90nEBN3fiiImpvRFJcODcWYTEf+est3HcRr1h90u9uf5sK2bqWwYwjc//8Ch8xkMhwYItQrjOTQDMyap9a/UB+/6+g8tZ3VoBHEULrWQb3r5ST5KXsjO44iwUJNRg3g139qZjORD4+RTyXv615XnAXaUs25Rl722PP1V5glIPt3RO21qdjuUCk9FtAf5GSORHaFQXUyWAvnYHeASn6MydlA1DXeNBbdqXZPIacvWcoGdZ+aJGHAIHuvRBUpmPwDRbNGKyayL5svPXMXFfNrDrVIfsHZi4+sK8ozBXTqmAPSdi/TkeZH5XHWiJmSv/jPuUksrA9f//OlWRQHlh25bI6M4j8mId44xq1hjBPVNTAZW3R3DZFfEk1CbIuzppQbEZHW4kv4bZ2TWRboLyesJpEXLzzzkoQ=
  email: false
