sudo: required
language: bash
services:
- docker
before_script:
- docker-compose build r-transformation
script: docker-compose run --rm --entrypoint sh -e KBC_DATA_DIR=/code/tests/data/
  r-transformation /code/run_tests.sh
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notification:
  slack:
    secure: oz+T3A3tuF5pVyxiw6MUvuPCJPSPGr3I7U43leNFE6ILCei15Arg5shSJbhixOf1uLpkm6Rgjou0x6klg+Yzlku3t7evoLXlwhE98H1baC8sm6XDUSGJ0Bf1y+vJIh+nLD0faD4HXCP0PQs1eb+LcYQ77CZT2J3HumdyzessveCrFSWD0u89kfVIyI8OPO91gI8zhCo9oKSVwAPVjQPA4JOX2WFHemySeBlcLFCKrUb4KhcuLDvTR7S6N0ZECHq6sU1BZg6hqVWUVq0OTBHb1ukSCu2FPXOhMcLvmWNECvgyoOE4YPuSKeoRm+yProRoefwYVVLcRcEAUP/PlMlz/E1qb2xCyFFJy9Vajz94gSjL8PTzBITyIqMBE2BDymayX70Lj1egeDGXegV1kSz2liOhkSnG1gvgdKhKfwU/9Jl6/tlsRgdfY7ZGMcD14gMqh/nGsX0++q0xTrD6Ev+TYG+XjNbR+wQCTOeWImQJHS2PhyMHFa7aMhA+Hfspl9+7Nx1rtIILscuEHdnVRq5kb2KV+eaqivTjUYXero8TRFrC1V+y7slNoMaP/OeInqyro7/aeOBkAwl5ECN1ufT7uzMuxnRyecUA/uOnevrOhyOkJVHJMLZ/u69jpZKtgYmdYa36Xqgg+Md7bl9R5X+HcpHnIFNEk7mgp6/iwhaa6os=
  email: false
