language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
 - keboola/r-application
 - keboola/r-docker-application

notifications:
  slack: keboola:eoqvo0RDzLRDPytuVEHRJNOc