sudo: required
language: bash
services:
- docker
before_script:
- docker-compose build r-transformation
script: docker-compose run --rm --entrypoint sh -e KBC_DATA_DIR=/code/tests/data/
  r-transformation /code/run_tests.sh
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notification:
  slack:
    rooms:
      secure: VacqAfzaMCT5KYFzeXx6zNeq+QYrkpPYKwkU7A+c8eSY3yWcZ1DMnEQ1eOmogGYoq5LNQTsvyo7KfgD3UZWB1/AH2BnbGE/6fq1Gg7/HkE8J2jMjUiRQiIU6ojDM4AC2FodKAdf1mWQ6xOeLvvs8SHSiGY4ZRFu9+sdn4gLK7wu2QNwEDTCIWbnRN8WtAcNHO0JTqXR4vO6ntmDScaQ++Ln0KWHVrjp5VD8VLy0LIdBgNdCMJNe5UwzcBg970tTY4v7dpb1k9T15/SF+j2WewywdZJbrZ60WXkveGR41gwPhpv4xuBVcYWk55rd6ymyoGsR24SM9XjwloEQB62p5Ta2yoy5Pg+0YLZsFPLArrHWCQ/fiux+VER7ThWuc0rnJcjW5Ywf5YbEZ2HOi3mwbzmb/6rCGyn2Ors9NVrAs0bQPVt9/5NLH2f41K1DMPzNqq80/GmgFpfJgJuX8neAYUMoKbhz5cIGstuzvDikZhDbD3UUMkqPCZzJpHbleaM75qawq/6iyhQWfiV88lthTbGbHbIGU0Qii+p5dYlWpqZy9TwEuGhwIq8QwoHdOHUwepSN7GnvBMY9lspoaeI8kVRMsV8SRbrNT7hjXu+WQu/tgP9aPoNxm/e3GXk5RadIOQZ6SE8OwLc/EbI8TjAJOygkrE83QuxecFpvPceocp+0=
