language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

r_github_packages:
 - keboola/r-application
 - keboola/r-docker-application

before_install:
 - curl -SL "http://curl.haxx.se/ca/cacert.pem" -o /usr/cacert.pem
 - export KBC_DATA_DIR=$TRAVIS_BUILD_DIR/tests/data/

notifications:
  slack: keboola:eoqvo0RDzLRDPytuVEHRJNOc