sudo: required
language: bash
services:
- docker
before_script:
- docker-compose build r-transformation
script: docker-compose run --rm --entrypoint sh -e KBC_DATA_DIR=/code/tests/data/
  r-transformation /code/run_tests.sh
after_success:
- docker images
deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    tags: true
notifications:
  slack:
    rooms:
      secure: iBVF5x4mWDYmRy0OQmQCWyV59cIW1pUYI3QIyUTAoXQo1OSjA9xRAl8qoLDTkHrfW3aZPYxRgiw1oo25s3vmXLiUhd9LAn1j3T+tHI8QkBzu7SbPm0BQ05VIQCYpG/BTpfo6Sb3Zf3Rpue1qK3NPy3jLccIq62gkzwGgKQuS709sVgJcXnp3XaA+cyNu1HOF+H3h817UyDF6eVulrl25ij+YJI75LC8h/QiyPN0h4yE5rl0pFBr2EINNw+9eDAv+fJ0Iq+POMEwLny6DFf8rQhU9S3L79le9rUFweIsXHiQutssUnLswMn9Gxb6vvBjC88O0KLXrcuZmomJ33KXlq0qv5Cn2JGXcntelEzEVyDznjY3oBJARoe9hN2gMCbZRnm/gjValfyYSqcwn41di6zyRPA3B2gXUKXZNle8ygXNuT9hxiLyTFh8Z44FhgaO9+nlHsJ7WoU4MpTMN8NOxWnZ5sf3x20Br6YkNJYVmX5eG157vcuS0sMzbqVXQtwDcuoNy3bwctxR359o6Rkce8f+OwW75owIbEy4wUHm1aMcjn631QMAYd4+5C4IYxNx91uCWrN4qUqvcQASt6gZChEVQ7d+H4l8KCiQO6t3mcKmNQ/iIDVsFZvAiec49oBBB/yJrcQBXRhgDzJwFGWySgLIkomL6UEY5mi3OOdlaumo=
  email: false
